# -*- coding: utf-8 -*-
"""CAR_PRICE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ni4PSmzZK0MXWjAFb7XbzFsc_QySukaY

# ***CAR PRICE PREDICTION APP***

## ***LOAD DATA***
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import StandardScaler
import pickle

car_data = pd.read_csv('/content/car_prediction_data.csv')
car_data.head()

car_data.shape

car_data.info()

"""## ***DATA PREPROCESSING***"""

car_data.isnull().sum()

car_data.duplicated().sum()

car_data.drop_duplicates(inplace=True)

car_data.duplicated().sum()

car_data.T.duplicated().sum()

"""### ***Outlier Detection and Handling***"""

num_cols = car_data.select_dtypes(include=np.number).columns.tolist()
num_cols

for col in num_cols:
    plt.figure()
    car_data.boxplot(column=col)
    plt.title(f'Outliers in {col}')
    plt.show()

print("Before:", car_data.shape)

for col in num_cols:
    Q1 = car_data[col].quantile(0.25)
    Q3 = car_data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5*IQR
    upper = Q3 + 1.5*IQR

    car_data = car_data[(car_data[col] >= lower) & (car_data[col] <= upper)]

plt.figure()
plt.boxplot(car_data[num_cols])
plt.title(('After Outlier Handling'))
plt.show()

print("After:", car_data.shape)

car_data.nunique()

"""### ***Feature Engineering***

### ***Encoding***
"""

cat_cols = ['Fuel_Type', 'Seller_Type', 'Transmission']
num_cols = ['Present_Price', 'Kms_Driven', 'Year', 'Owner']

name_encoder = LabelEncoder()
car_data['Car_Name'] = name_encoder.fit_transform(car_data['Car_Name'])

car_data = pd.get_dummies(car_data, columns=cat_cols, drop_first=True)

car_data.head()

"""### ***Train-Test Split***"""

X = car_data.drop('Selling_Price', axis=1)
y = car_data['Selling_Price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print(X.columns)

"""### ***Scaling***"""

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""## ***Model Development***

### ***Linear Regression***
"""

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

rf = RandomForestRegressor(random_state=42)
rf.fit(X_train, y_train)

print("Default RF R2:", rf.score(X_test, y_test))

"""## ***Hyper Parameter Tuning***"""

param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False]
}

random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=10,
    cv=5,
    scoring='r2',
    random_state=42,
    n_jobs=-1
)

random_search.fit(X_train, y_train)

print("Best Parameters:", random_search.best_params_)
print("Best CV Score:", random_search.best_score_)

best_rf = random_search.best_estimator_

from sklearn.metrics import r2_score, mean_absolute_error

y_pred_tuned = best_rf.predict(X_test)

print("Tuned RF R2:", r2_score(y_test, y_pred_tuned))
print("Tuned RF MAE:", mean_absolute_error(y_test, y_pred_tuned))

print("Linear Regression R2:", lr.score(X_test, y_test))
print("Default RF R2:", rf.score(X_test, y_test))
print("Tuned RF R2:", best_rf.score(X_test, y_test))

if rf.score(X_test, y_test) > lr.score(X_test, y_test):
    print("Random Forest is the best model")
    best_model = rf
else:
    print("Linear Regression is the best model")
    best_model = lr

import pickle
pickle.dump(best_model, open("best_model.pkl", "wb"))
pickle.dump(scaler, open("scaler.pkl", "wb"))
pickle.dump(name_encoder, open('name_encoder.pkl', 'wb'))